[project]
name = "dcf"
version = "0.1.0"
description = "Simple DCF tool in Python to analyze US stocks through yfinance"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "yfinance>=0.2.32",
    "pandas>=2.0.0",
]
